baseURL = 'https://kyokorone.github.io/wpe-journal/'
languageCode = 'en-us'
title = 'WPE Online Journal'
author = "Angela Sol Henson"
copyright = "Angela Sol Henson"
paginate = 10
theme = "tailwind"

[params]
# dir name of your blog content (default is `content/posts`).
# the list of set content will show up on your index page (baseurl).
contentTypeName = "posts"
toc = false
DateFormatList = "January 2, 2006 03:04PM"

[params.header]
logo = "logo.webp"

[params.footer]
since = 2023
poweredby = true

[menu]

[[menu.main]]
identifier = "post"
name = "Posts"
pageRef = "/posts"
weight = 0

[taxonomies]
category = "categories"
tag = "tags"
